<Project Sdk="Microsoft.NET.Sdk.Web">
<PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<WarningsAsErrors></WarningsAsErrors>
	<NoWarn>$(NoWarn);NU1901;NU1902;NU1903;NU1904</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" Version="9.1.2" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
	  <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.7" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.7">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
	  <PackageReference Include="Npgsql" Version="10.0.2" />
	  <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\logiMarket.Shared\logiMarket.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Application\Orders\Queries\" />
  </ItemGroup>
</Project>
